#ifndef CONVEX_HULL_FILTERING_INCLUDE_CONVEX_HULL_FILTERING_CONFIG_HPP_
#define CONVEX_HULL_FILTERING_INCLUDE_CONVEX_HULL_FILTERING_CONFIG_HPP_

namespace convex_hull_filtering {
const float EPSILON = 1e-6;
}  // namespace convex_hull_filtering

#endif  // CONVEX_HULL_FILTERING_INCLUDE_CONVEX_HULL_FILTERING_CONFIG_HPP_
